import {
  ICardData,
  IBudgetsCategory,
  ITransactions,
  ITransactionsTableData,
  type ISavingsTableData,
  type ISavingsCategory,
  type ISavings,
} from './interfaces';
import { getRandomDateWithinLast10Days } from './helper-funtion';
export const CardDetails: ICardData[] = [
  {
    title: 'Total Balance',
    amount: 120000,
    description: 'Total balance for',
    icon: 'fa-piggy-bank',
    iconBg: '#E1BFF399',
    percentage: 100,
  },
  {
    title: 'Total Income',
    amount: 500000,
    description: 'Total income for',
    icon: 'fa-hand-holding-dollar',
    iconBg: '#048E3B1A',
    percentage: 41.7,
  },
  {
    title: 'Total Expenses',
    amount: 400000,
    description: 'Total expenses for ',
    icon: 'fa-money-bill-transfer',
    iconBg: '#DFA2261A',
    percentage: 33.3,
  },

  {
    title: 'Top Category',
    amount: 800000000000000,
    description: 'Top expenses for',
    icon: 'fa-money-bill-trend-up',
    iconBg: '#E113131A',
    percentage: 25,
  },
];

export const CustomersMockData = [
  {
    id: 1,
    customerName: 'John Doe',
    phoneNumber: '080678473892',
    accountNumber: '1234567890',
    email: 'johndoe@yahoo.com',
    customerId: 'CUST001',
    status: 'whitelist',
    lastActive: '2023-10-01',
    dateRegistered: '2023-01-15',
    isStaff: 'Staff',
  },
  {
    id: 2,
    customerName: 'Jane Smith',
    phoneNumber: '080123456789',
    accountNumber: '2345678901',
    email: 'janesmith@gmail.com',
    customerId: 'CUST002',
    status: 'hotlist',
    lastActive: '2023-09-20',
    dateRegistered: '2022-12-05',
    isStaff: 'Customer',
  },
  {
    id: 3,
    customerName: 'Michael Johnson',
    phoneNumber: '081234567890',
    accountNumber: '3456789012',
    email: 'mjohnson@outlook.com',
    customerId: 'CUST003',
    status: 'whitelist',
    lastActive: '2023-10-11',
    dateRegistered: '2023-02-10',
    isStaff: 'Customer',
  },
  {
    id: 4,
    customerName: 'Emily Davis',
    phoneNumber: '070987654321',
    accountNumber: '4567890123',
    email: 'emily.davis@gmail.com',
    customerId: 'CUST004',
    status: 'whitelist',
    lastActive: '2023-08-05',
    dateRegistered: '2023-01-30',
    isStaff: 'Staff',
  },
  {
    id: 5,
    customerName: 'David Wilson',
    phoneNumber: '08011112222',
    accountNumber: '5678901234',
    email: 'davidwilson@yahoo.com',
    customerId: 'CUST005',
    status: 'hotlist',
    lastActive: '2023-07-19',
    dateRegistered: '2022-11-25',
    isStaff: 'Staff',
  },
  {
    id: 6,
    customerName: 'Olivia Brown',
    phoneNumber: '09022334455',
    accountNumber: '6789012345',
    email: 'olivia.brown@hotmail.com',
    customerId: 'CUST006',
    status: 'whitelist',
    lastActive: '2023-10-02',
    dateRegistered: '2023-03-15',
    isStaff: 'Customer',
  },
  {
    id: 7,
    customerName: 'Daniel Taylor',
    phoneNumber: '08199887766',
    accountNumber: '7890123456',
    email: 'danieltaylor@gmail.com',
    customerId: 'CUST007',
    status: 'hotlist',
    lastActive: '2023-09-30',
    dateRegistered: '2023-01-10',
    isStaff: 'Staff',
  },
  {
    id: 8,
    customerName: 'Sophia Anderson',
    phoneNumber: '08034445566',
    accountNumber: '8901234567',
    email: 'sophia.a@gmail.com',
    customerId: 'CUST008',
    status: 'hotlist',
    lastActive: '2023-06-25',
    dateRegistered: '2022-10-01',
    isStaff: 'Customer',
  },
  {
    id: 9,
    customerName: 'James Thomas',
    phoneNumber: '07012223344',
    accountNumber: '9012345678',
    email: 'jamesthomas@protonmail.com',
    customerId: 'CUST009',
    status: 'whitelist',
    lastActive: '2023-10-05',
    dateRegistered: '2023-04-01',
    isStaff: 'Customer',
  },
  {
    id: 10,
    customerName: 'Ava Martinez',
    phoneNumber: '09087776655',
    accountNumber: '0123456789',
    email: 'avamartinez@mail.com',
    customerId: 'CUST010',
    status: 'hotlist',
    lastActive: '2023-09-18',
    dateRegistered: '2023-02-20',
    isStaff: 'Staff',
  },
];

export const TransactionsMockTableData: ITransactionsTableData[] = [
  {
    transactionId: 'TXN-1001',
    date: getRandomDateWithinLast10Days(10),
    description: 'Groceries at Shoprite',
    category: 'Food Stuffs',
    amount: 18500,
    type: 'Expense',
    paymentMethod: 'Credit Card',
  },
  {
    transactionId: 'TXN-1002',
    date: getRandomDateWithinLast10Days(10),
    description: 'Salary Payment',
    category: 'Income',
    amount: 250000,
    type: 'Income',
    paymentMethod: 'Bank Transfer',
  },
  {
    transactionId: 'TXN-1003',
    date: getRandomDateWithinLast10Days(10),
    description: 'Electricity Bill (PHCN)',
    category: 'Utilities',
    amount: 12000,
    type: 'Expense',
    paymentMethod: 'Bank Transfer',
  },
  {
    transactionId: 'TXN-1004',
    date: getRandomDateWithinLast10Days(10),
    description: 'Netflix Subscription',
    category: 'Entertainment',
    amount: 4500,
    type: 'Expense',
    paymentMethod: 'Debit Card',
  },
  {
    transactionId: 'TXN-1005',
    date: getRandomDateWithinLast10Days(10),
    description: 'Transport Allowance',
    category: 'Income',
    amount: 15000,
    type: 'Income',
    paymentMethod: 'Cash',
  },
  {
    transactionId: 'TXN-1006',
    date: getRandomDateWithinLast10Days(10),
    description: 'Fuel Purchase',
    category: 'Transportation',
    amount: 10000,
    type: 'Expense',
    paymentMethod: 'Credit Card',
  },
  {
    transactionId: 'TXN-1007',
    date: getRandomDateWithinLast10Days(10),
    description: 'Freelance Project Payment',
    category: 'Income',
    amount: 80000,
    type: 'Income',
    paymentMethod: 'Bank Transfer',
  },
  {
    transactionId: 'TXN-1008',
    date: getRandomDateWithinLast10Days(10),
    description: 'Airtime Recharge',
    category: 'Utilities',
    amount: 3000,
    type: 'Expense',
    paymentMethod: 'Mobile Payment',
  },
  {
    transactionId: 'TXN-1009',
    date: getRandomDateWithinLast10Days(10),
    description: 'Restaurant Dinner',
    category: 'Restaurant & Dining',
    amount: 9500,
    type: 'Expense',
    paymentMethod: 'Debit Card',
  },
  {
    transactionId: 'TXN-1010',
    date: getRandomDateWithinLast10Days(10),
    description: 'Internet Subscription (Spectranet)',
    category: 'Utilities',
    amount: 18000,
    type: 'Expense',
    paymentMethod: 'Bank Transfer',
  },
  {
    transactionId: 'TXN-1011',
    date: getRandomDateWithinLast10Days(10),
    description: 'Dividend Payout',
    category: 'Income',
    amount: 22000,
    type: 'Income',
    paymentMethod: 'Bank Transfer',
  },
  {
    transactionId: 'TXN-1012',
    date: getRandomDateWithinLast10Days(10),
    description: 'Clothing Purchase',
    category: 'Shopping',
    amount: 27000,
    type: 'Expense',
    paymentMethod: 'Credit Card',
  },
  {
    transactionId: 'TXN-1013',
    date: getRandomDateWithinLast10Days(10),
    description: 'Gym Membership',
    category: 'Healthcare',
    amount: 15000,
    type: 'Expense',
    paymentMethod: 'Debit Card',
  },
  {
    transactionId: 'TXN-1014',
    date: getRandomDateWithinLast10Days(10),
    description: 'Bonus Payment',
    category: 'Income',
    amount: 50000,
    type: 'Income',
    paymentMethod: 'Bank Transfer',
  },
  {
    transactionId: 'TXN-1015',
    date: getRandomDateWithinLast10Days(10),
    description: 'Pharmacy Purchase',
    category: 'Healthcare',
    amount: 6500,
    type: 'Expense',
    paymentMethod: 'Cash',
  },
  {
    transactionId: 'TXN-1016',
    date: getRandomDateWithinLast10Days(10),
    description: 'Rent Payment',
    category: 'Rent',
    amount: 30000,
    type: 'Expense',
    paymentMethod: 'Bank Transfer',
  },
];

export const Categories = [
  'Food Stuffs',
  'Utilities',
  'Entertainment',
  'Transportation',
  'Healthcare',
  'Shopping',
  'Restaurant & Dining',
  'Income',
];

export const BudgetCategoryData: IBudgetsCategory[] = [
  {
    id: 1,
    budgetCategory: 'Food Stuffs',
    amountBudgeted: 25000,
    amountSpent: 0,
    icon: 'fa-bowl-food',
    iconColor: 'text-green-600',
    iconBg: 'bg-green-100',
  },
  {
    id: 2,
    budgetCategory: 'Family',
    amountBudgeted: 20000,
    amountSpent: 0,
    icon: 'fa-people-roof',
    iconColor: 'text-blue-600',
    iconBg: 'bg-blue-100',
  },
  {
    id: 3,
    budgetCategory: 'Rent',
    amountBudgeted: 40000,
    amountSpent: 0,
    icon: 'fa-house',
    iconColor: 'text-purple-400',
    iconBg: 'bg-purple-100',
  },
  {
    id: 4,
    budgetCategory: 'Transportation',
    amountBudgeted: 12000,
    amountSpent: 0,
    icon: 'fa-truck-arrow-right',
    iconColor: 'text-yellow-600',
    iconBg: 'bg-yellow-100',
  },
  {
    id: 5,
    budgetCategory: 'Toiletries',
    amountBudgeted: 6000,
    amountSpent: 0,
    icon: 'fa-toilet-portable',
    iconColor: 'text-pink-600',
    iconBg: 'bg-pink-100',
  },
  {
    id: 6,
    budgetCategory: 'Restaurant & Dining',
    amountBudgeted: 15000,
    amountSpent: 0,
    icon: 'fa-utensils',
    iconColor: 'text-red-600',
    iconBg: 'bg-red-100',
  },
  {
    id: 7,
    budgetCategory: 'Bills & Subscriptions',
    amountBudgeted: 10000,
    amountSpent: 0,
    icon: 'fa-money-bills',
    iconColor: 'text-indigo-500',
    iconBg: 'bg-indigo-100',
  },
  {
    id: 8,
    budgetCategory: 'Entertainment',
    amountBudgeted: 6000,
    amountSpent: 0,
    icon: 'fa-champagne-glasses',
    iconColor: 'text-teal-600',
    iconBg: 'bg-teal-100',
  },
  {
    id: 9,
    budgetCategory: 'Utilities',
    amountBudgeted: 5000,
    amountSpent: 0,
    icon: 'fa-lightbulb',
    iconColor: 'text-orange-600',
    iconBg: 'bg-orange-100',
  },
  {
    id: 10,
    budgetCategory: 'Healthcare',
    amountBudgeted: 8000,
    amountSpent: 0,
    icon: 'fa-briefcase-medical',
    iconColor: 'text-cyan-600',
    iconBg: 'bg-cyan-100',
  },
  {
    id: 11,
    budgetCategory: 'Education',
    amountBudgeted: 8000,
    amountSpent: 0,
    icon: 'fa-user-graduate',
    iconColor: 'text-lime-600',
    iconBg: 'bg-lime-100',
  },
  {
    id: 12,
    budgetCategory: 'Shopping',
    amountBudgeted: 2000,
    amountSpent: 0,
    icon: 'fa-cart-shopping',
    iconColor: 'text-amber-600',
    iconBg: 'bg-amber-100',
  },
  {
    id: 13,
    budgetCategory: 'Travel',
    amountBudgeted: 3000,
    amountSpent: 0,
    icon: 'fa-plane',
    iconColor: 'text-fuchsia-600',
    iconBg: 'bg-fuchsia-100',
  },
  {
    id: 14,
    budgetCategory: 'Personal Care',
    amountBudgeted: 2000,
    amountSpent: 0,
    icon: 'fa-person-cane',
    iconColor: 'text-rose-600',
    iconBg: 'bg-rose-100',
  },
  {
    id: 15,
    budgetCategory: 'Gifts & Donations',
    amountBudgeted: 2000,
    amountSpent: 0,
    icon: 'fa-gifts',
    iconColor: 'text-sky-600',
    iconBg: 'bg-sky-100',
  },
  {
    id: 16,
    budgetCategory: 'Loan',
    amountBudgeted: 1000,
    amountSpent: 0,
    icon: 'fa-hand-holding-dollar',
    iconColor: 'text-stone-600',
    iconBg: 'bg-stone-100',
  },
  {
    id: 17,
    budgetCategory: 'Miscellaneous',
    amountBudgeted: 1000,
    amountSpent: 0,
    icon: 'fa-money-bill-transfer',
    iconColor: 'text-slate-600',
    iconBg: 'bg-slate-100',
  },
];

export const MockSavingsCategory: ISavingsCategory[] = [
  {
    id: 1,
    name: 'Transportation & Vehicles',
    icon: 'fa-car-side',
    iconColor: 'text-green-600',
    iconBg: 'bg-green-100',
  },
  {
    id: 2,
    name: 'Housing & Living',
    icon: 'fa-home',
    iconColor: 'text-purple-500',
    iconBg: 'bg-purple-100',
  },
  {
    id: 3,
    name: 'Personal & Lifestyle',
    icon: 'fa-person-walking',
    iconColor: 'text-pink-600',
    iconBg: 'bg-pink-100',
  },
  {
    id: 4,
    name: 'Education & Self-Development',
    icon: 'fa-user-graduate',
    iconColor: 'text-lime-600',
    iconBg: 'bg-lime-100',
  },
  {
    id: 5,
    name: 'Travel & Leisure',
    icon: 'fa-plane',
    iconColor: 'text-fuchsia-600',
    iconBg: 'bg-fuchsia-100',
  },
  {
    id: 6,
    name: 'Health & Wellness',
    icon: 'fa-briefcase-medical',
    iconColor: 'text-red-600',
    iconBg: 'bg-red-100',
  },
  {
    id: 7,
    name: 'Family & Dependents',
    icon: 'fa-people-group',
    iconColor: 'text-orange-600',
    iconBg: 'bg-orange-100',
  },
  {
    id: 8,
    name: 'Technology & Gadgets',
    icon: 'fa-computer',
    iconColor: 'text-cyan-600',
    iconBg: 'bg-cyan-100',
  },
  {
    id: 9,
    name: 'Financial Goals',
    icon: 'fa-money-bill-trend-up',
    iconColor: 'text-teal-600',
    iconBg: 'bg-teal-100',
  },
  {
    id: 10,
    name: 'Entertainment & Fun',
    icon: 'fa-champagne-glasses',
    iconColor: 'text-emerald-600',
    iconBg: 'bg-emerald-100',
  },
  {
    id: 11,
    name: 'Business & Entrepreneurship',
    icon: 'fa-business-time',
    iconColor: 'text-stone-600',
    iconBg: 'bg-stone-100',
  },
  {
    id: 12,
    name: 'Wedding & Events',
    icon: 'fa-hand-holding-heart',
    iconColor: 'text-rose-600',
    iconBg: 'bg-rose-100',
  },
  {
    id: 13,
    name: 'Charity & Donations',
    icon: 'fa-hands-holding-circle',
    iconColor: 'text-amber-600',
    iconBg: 'bg-amber-100',
  },
  {
    id: 14,
    name: 'Emergency Funds',
    icon: 'fa-person-drowning',
    iconColor: 'text-sky-600',
    iconBg: 'bg-sky-100',
  },
  {
    id: 15,
    name: 'Beauty & Fashion',
    icon: 'fa-store',
    iconColor: 'text-pink-800',
    iconBg: 'bg-pink-200',
  },
  {
    id: 16,
    name: 'Others',
    icon: 'fa-universal-access',
    iconColor: 'text-gray-600',
    iconBg: 'bg-gray-100',
  },
];

export const MockSavingsData: ISavings[] = [
  {
    id: 1,
    title: 'New Car Fund',
    description: 'Saving towards buying a Toyota Corolla',
    savingCategoryId: 1,
    amountSaved: 0,
    targetAmount: 100000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 2,
    title: 'House Rent',
    description: 'Annual rent savings for apartment',
    savingCategoryId: 2,
    amountSaved: 0,
    targetAmount: 5000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 3,
    title: 'Fitness Program',
    description: 'Gym membership and wellness program',
    savingCategoryId: 3,
    amountSaved: 0,
    targetAmount: 12000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 4,
    title: 'Vacation to Paris',
    description: 'Summer trip to Europe',
    savingCategoryId: 5,
    amountSaved: 0,
    targetAmount: 100000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 5,
    title: 'Emergency Fund',
    description: '3 months of living expenses',
    savingCategoryId: 9,
    amountSaved: 0,
    targetAmount: 10000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 6,
    title: 'New iPhone',
    description: 'Saving towards iPhone 16 Pro',
    savingCategoryId: 8,
    amountSaved: 0,
    targetAmount: 70000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 7,
    title: 'Wedding Ceremony',
    description: 'Saving for wedding event',
    savingCategoryId: 12,
    amountSaved: 0,
    targetAmount: 200000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 8,
    title: 'MBA Tuition',
    description: 'Self-development course fee',
    savingCategoryId: 4,
    amountSaved: 0,
    targetAmount: 12000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 9,
    title: 'Christmas Shopping',
    description: 'Holiday gifts and family treats',
    savingCategoryId: 10,
    amountSaved: 0,
    targetAmount: 2000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 10,
    title: 'Startup Capital',
    description: 'Initial funds for new business venture',
    savingCategoryId: 11,
    amountSaved: 0,
    targetAmount: 25000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 11,
    title: 'House Purchase',
    description: 'Initial funds for new home',
    savingCategoryId: 2,
    amountSaved: 0,
    targetAmount: 70000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 12,
    title: 'Health Insurance',
    description: 'Initial funds for health insurance',
    savingCategoryId: 6,
    amountSaved: 0,
    targetAmount: 100000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 13,
    title: 'Misellaneous Expenses',
    description: 'Funds for misellaneous expenses',
    savingCategoryId: 14,
    amountSaved: 0,
    targetAmount: 50000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 14,
    title: 'New Laptop',
    description: 'Saving towards new Laptop',
    savingCategoryId: 8,
    amountSaved: 0,
    targetAmount: 50000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
  {
    id: 15,
    title: 'Charity Fund',
    description: 'Saving towards charity donations',
    savingCategoryId: 13,
    amountSaved: 0,
    targetAmount: 20000,
    status: 'In Progress',
    date: getRandomDateWithinLast10Days(10),
  },
];

export const MockSavingsTableData: ISavingsTableData[] = [
  {
    id: 1,
    savingsId: 1,
    savingCategoryId: 1,
    amount: 50000,
    date: getRandomDateWithinLast10Days(10),
    description: 'Initial deposit for car savings',
    type: 'Deposit',
  },
  {
    id: 2,
    savingsId: 1,
    savingCategoryId: 1,
    amount: 15000,
    date: getRandomDateWithinLast10Days(10),
    description: 'Monthly contribution',
    type: 'Deposit',
  },
  {
    id: 3,
    savingsId: 4,
    savingCategoryId: 5,
    amount: 20000,
    date: getRandomDateWithinLast10Days(10),
    description: 'Holiday trip to Paris',
    type: 'Deposit',
  },
  {
    id: 4,
    savingsId: 12,
    savingCategoryId: 6,
    withdrawal: 'Withdrawal',
    amount: 10000,
    date: getRandomDateWithinLast10Days(10),
    description: 'Unexpected medical bill',
    type: 'Deposit',
  },
  {
    id: 5,
    savingsId: 11,
    savingCategoryId: 2,
    amount: 75000,
    date: getRandomDateWithinLast10Days(10),
    description: 'First savings for house down payment',
    type: 'Deposit',
  },
  {
    id: 6,
    savingsId: 4,
    savingCategoryId: 5,
    withdrawal: 'Withdrawal',
    amount: 5000,
    date: getRandomDateWithinLast10Days(10),
    description: 'Bought flight tickets',
    type: 'Withdrawal',
  },
  {
    id: 7,
    savingsId: 8,
    savingCategoryId: 4,
    amount: 12000,
    date: getRandomDateWithinLast10Days(10),
    description: 'Tuition savings deposit',
    type: 'Deposit',
  },
  {
    id: 8,
    savingsId: 8,
    savingCategoryId: 4,
    amount: 3000,
    withdrawal: 'Withdrawal',
    date: getRandomDateWithinLast10Days(10),
    description: 'Books and materials',
    type: 'Withdrawal',
  },
  {
    id: 9,
    savingsId: 7,
    savingCategoryId: 12,
    amount: 25000,
    date: getRandomDateWithinLast10Days(10),
    description: 'Wedding savings deposit',
    type: 'Deposit',
  },
  {
    id: 10,
    savingsId: 7,
    savingCategoryId: 12,
    amount: 7000,
    withdrawal: 'Withdrawal',
    date: getRandomDateWithinLast10Days(10),
    description: 'Venue booking advance',
    type: 'Withdrawal',
  },
  {
    id: 11,
    savingsId: 10,
    savingCategoryId: 11,
    amount: 40000,
    date: getRandomDateWithinLast10Days(10),
    description: 'Start-up capital savings',
    type: 'Deposit',
  },
  {
    id: 12,
    savingsId: 10,
    savingCategoryId: 11,
    amount: 10000,

    date: getRandomDateWithinLast10Days(10),
    description: 'Purchase of business equipment',
    type: 'Deposit',
  },
  {
    id: 13,
    savingsId: 14,
    savingCategoryId: 8,
    amount: 8000,
    date: getRandomDateWithinLast10Days(10),
    description: 'Deposit for new laptop',
    type: 'Deposit',
  },
  {
    id: 14,
    savingsId: 15,
    savingCategoryId: 13,
    amount: 6000,
    date: getRandomDateWithinLast10Days(10),
    description: 'Savings for donation',
    type: 'Deposit',
  },
  {
    id: 15,
    savingsId: 15,
    savingCategoryId: 13,
    amount: 2000,
    withdrawal: 'Withdrawal',
    date: getRandomDateWithinLast10Days(10),
    description: 'Donation sent to orphanage',
    type: 'Withdrawal',
  },
];
