import {
  ICardData,
  type IBudgetsCategory,
  type ITransactions,
  type ITransactionsTableData,
} from './interfaces';
import { getRandomDateWithinLast10Days } from './helper-funtion';
export const CardDetails: ICardData[] = [
  {
    title: 'Total Balance',
    amount: 120000,
    description: 'Total balance for',
    icon: 'fa-piggy-bank',
    iconBg: '#E1BFF399',
    percentage: 100,
  },
  {
    title: 'Total Income',
    amount: 500000,
    description: 'Total income for',
    icon: 'fa-hand-holding-dollar',
    iconBg: '#048E3B1A',
    percentage: 41.7,
  },
  {
    title: 'Total Expenses',
    amount: 400000,
    description: 'Total expenses for ',
    icon: 'fa-money-bill-transfer',
    iconBg: '#DFA2261A',
    percentage: 33.3,
  },

  {
    title: 'Top Category',
    amount: 800000000000000,
    description: 'Top expenses for',
    icon: 'fa-money-bill-trend-up',
    iconBg: '#E113131A',
    percentage: 25,
  },
];

export const CustomersMockData = [
  {
    id: 1,
    customerName: 'John Doe',
    phoneNumber: '080678473892',
    accountNumber: '1234567890',
    email: 'johndoe@yahoo.com',
    customerId: 'CUST001',
    status: 'whitelist',
    lastActive: '2023-10-01',
    dateRegistered: '2023-01-15',
    isStaff: 'Staff',
  },
  {
    id: 2,
    customerName: 'Jane Smith',
    phoneNumber: '080123456789',
    accountNumber: '2345678901',
    email: 'janesmith@gmail.com',
    customerId: 'CUST002',
    status: 'hotlist',
    lastActive: '2023-09-20',
    dateRegistered: '2022-12-05',
    isStaff: 'Customer',
  },
  {
    id: 3,
    customerName: 'Michael Johnson',
    phoneNumber: '081234567890',
    accountNumber: '3456789012',
    email: 'mjohnson@outlook.com',
    customerId: 'CUST003',
    status: 'whitelist',
    lastActive: '2023-10-11',
    dateRegistered: '2023-02-10',
    isStaff: 'Customer',
  },
  {
    id: 4,
    customerName: 'Emily Davis',
    phoneNumber: '070987654321',
    accountNumber: '4567890123',
    email: 'emily.davis@gmail.com',
    customerId: 'CUST004',
    status: 'whitelist',
    lastActive: '2023-08-05',
    dateRegistered: '2023-01-30',
    isStaff: 'Staff',
  },
  {
    id: 5,
    customerName: 'David Wilson',
    phoneNumber: '08011112222',
    accountNumber: '5678901234',
    email: 'davidwilson@yahoo.com',
    customerId: 'CUST005',
    status: 'hotlist',
    lastActive: '2023-07-19',
    dateRegistered: '2022-11-25',
    isStaff: 'Staff',
  },
  {
    id: 6,
    customerName: 'Olivia Brown',
    phoneNumber: '09022334455',
    accountNumber: '6789012345',
    email: 'olivia.brown@hotmail.com',
    customerId: 'CUST006',
    status: 'whitelist',
    lastActive: '2023-10-02',
    dateRegistered: '2023-03-15',
    isStaff: 'Customer',
  },
  {
    id: 7,
    customerName: 'Daniel Taylor',
    phoneNumber: '08199887766',
    accountNumber: '7890123456',
    email: 'danieltaylor@gmail.com',
    customerId: 'CUST007',
    status: 'hotlist',
    lastActive: '2023-09-30',
    dateRegistered: '2023-01-10',
    isStaff: 'Staff',
  },
  {
    id: 8,
    customerName: 'Sophia Anderson',
    phoneNumber: '08034445566',
    accountNumber: '8901234567',
    email: 'sophia.a@gmail.com',
    customerId: 'CUST008',
    status: 'hotlist',
    lastActive: '2023-06-25',
    dateRegistered: '2022-10-01',
    isStaff: 'Customer',
  },
  {
    id: 9,
    customerName: 'James Thomas',
    phoneNumber: '07012223344',
    accountNumber: '9012345678',
    email: 'jamesthomas@protonmail.com',
    customerId: 'CUST009',
    status: 'whitelist',
    lastActive: '2023-10-05',
    dateRegistered: '2023-04-01',
    isStaff: 'Customer',
  },
  {
    id: 10,
    customerName: 'Ava Martinez',
    phoneNumber: '09087776655',
    accountNumber: '0123456789',
    email: 'avamartinez@mail.com',
    customerId: 'CUST010',
    status: 'hotlist',
    lastActive: '2023-09-18',
    dateRegistered: '2023-02-20',
    isStaff: 'Staff',
  },
];

export const TransactionsMockTableData: ITransactionsTableData[] = [
  {
    transactionId: 'TXN-1001',
    date: getRandomDateWithinLast10Days(10),
    description: 'Groceries at Shoprite',
    category: 'Food Stuffs',
    amount: 18500,
    type: 'Expense',
    paymentMethod: 'Credit Card',
  },
  {
    transactionId: 'TXN-1002',
    date: getRandomDateWithinLast10Days(10),
    description: 'Salary Payment',
    category: 'Income',
    amount: 250000,
    type: 'Income',
    paymentMethod: 'Bank Transfer',
  },
  {
    transactionId: 'TXN-1003',
    date: getRandomDateWithinLast10Days(10),
    description: 'Electricity Bill (PHCN)',
    category: 'Utilities',
    amount: 12000,
    type: 'Expense',
    paymentMethod: 'Bank Transfer',
  },
  {
    transactionId: 'TXN-1004',
    date: getRandomDateWithinLast10Days(10),
    description: 'Netflix Subscription',
    category: 'Entertainment',
    amount: 4500,
    type: 'Expense',
    paymentMethod: 'Debit Card',
  },
  {
    transactionId: 'TXN-1005',
    date: getRandomDateWithinLast10Days(10),
    description: 'Transport Allowance',
    category: 'Income',
    amount: 15000,
    type: 'Income',
    paymentMethod: 'Cash',
  },
  {
    transactionId: 'TXN-1006',
    date: getRandomDateWithinLast10Days(10),
    description: 'Fuel Purchase',
    category: 'Transportation',
    amount: 10000,
    type: 'Expense',
    paymentMethod: 'Credit Card',
  },
  {
    transactionId: 'TXN-1007',
    date: getRandomDateWithinLast10Days(10),
    description: 'Freelance Project Payment',
    category: 'Income',
    amount: 80000,
    type: 'Income',
    paymentMethod: 'Bank Transfer',
  },
  {
    transactionId: 'TXN-1008',
    date: getRandomDateWithinLast10Days(10),
    description: 'Airtime Recharge',
    category: 'Utilities',
    amount: 3000,
    type: 'Expense',
    paymentMethod: 'Mobile Payment',
  },
  {
    transactionId: 'TXN-1009',
    date: getRandomDateWithinLast10Days(10),
    description: 'Restaurant Dinner',
    category: 'Restaurant & Dining',
    amount: 9500,
    type: 'Expense',
    paymentMethod: 'Debit Card',
  },
  {
    transactionId: 'TXN-1010',
    date: getRandomDateWithinLast10Days(10),
    description: 'Internet Subscription (Spectranet)',
    category: 'Utilities',
    amount: 18000,
    type: 'Expense',
    paymentMethod: 'Bank Transfer',
  },
  {
    transactionId: 'TXN-1011',
    date: getRandomDateWithinLast10Days(10),
    description: 'Dividend Payout',
    category: 'Income',
    amount: 22000,
    type: 'Income',
    paymentMethod: 'Bank Transfer',
  },
  {
    transactionId: 'TXN-1012',
    date: getRandomDateWithinLast10Days(10),
    description: 'Clothing Purchase',
    category: 'Shopping',
    amount: 27000,
    type: 'Expense',
    paymentMethod: 'Credit Card',
  },
  {
    transactionId: 'TXN-1013',
    date: getRandomDateWithinLast10Days(10),
    description: 'Gym Membership',
    category: 'Healthcare',
    amount: 15000,
    type: 'Expense',
    paymentMethod: 'Debit Card',
  },
  {
    transactionId: 'TXN-1014',
    date: getRandomDateWithinLast10Days(10),
    description: 'Bonus Payment',
    category: 'Income',
    amount: 50000,
    type: 'Income',
    paymentMethod: 'Bank Transfer',
  },
  {
    transactionId: 'TXN-1015',
    date: getRandomDateWithinLast10Days(10),
    description: 'Pharmacy Purchase',
    category: 'Healthcare',
    amount: 6500,
    type: 'Expense',
    paymentMethod: 'Cash',
  },
  {
    transactionId: 'TXN-1016',
    date: getRandomDateWithinLast10Days(10),
    description: 'Rent Payment',
    category: 'Rent',
    amount: 30000,
    type: 'Expense',
    paymentMethod: 'Bank Transfer',
  },
];

export const Categories = [
  'Food Stuffs',
  'Utilities',
  'Entertainment',
  'Transportation',
  'Healthcare',
  'Shopping',
  'Restaurant & Dining',
  'Income',
];

export const BudgetCategoryData: IBudgetsCategory[] = [
  {
    id: 1,
    budgetCategory: 'Food Stuffs',
    amountBudgeted: 25000,
    amountSpent: 0,
  },
  {
    id: 2,
    budgetCategory: 'Family',
    amountBudgeted: 20000,
    amountSpent: 0,
  },
  {
    id: 3,
    budgetCategory: 'Rent',
    amountBudgeted: 40000,
    amountSpent: 0,
  },
  {
    id: 4,
    budgetCategory: 'Transportation',
    amountBudgeted: 12000,
    amountSpent: 0,
  },
  {
    id: 5,
    budgetCategory: 'Toiletries',
    amountBudgeted: 6000,
    amountSpent: 0,
  },
  {
    id: 6,
    budgetCategory: 'Restaurant & Dining',
    amountBudgeted: 15000,
    amountSpent: 0,
  },
  {
    id: 7,
    budgetCategory: 'Bills & Subscriptions',
    amountBudgeted: 10000,
    amountSpent: 0,
  },
  {
    id: 8,
    budgetCategory: 'Entertainment',
    amountBudgeted: 6000,
    amountSpent: 0,
  },
  {
    id: 9,
    budgetCategory: 'Utilities',
    amountBudgeted: 5000,
    amountSpent: 0,
  },
  {
    id: 10,
    budgetCategory: 'Healthcare',
    amountBudgeted: 8000,
    amountSpent: 0,
  },
  {
    id: 11,
    budgetCategory: 'Education',
    amountBudgeted: 8000,
    amountSpent: 0,
  },
  {
    id: 12,
    budgetCategory: 'Shopping',
    amountBudgeted: 2000,
    amountSpent: 0,
  },
  {
    id: 13,
    budgetCategory: 'Travel',
    amountBudgeted: 3000,
    amountSpent: 0,
  },
  {
    id: 14,
    budgetCategory: 'Personal Care',
    amountBudgeted: 2000,
    amountSpent: 0,
  },
  {
    id: 15,
    budgetCategory: 'Gifts & Donations',
    amountBudgeted: 2000,
    amountSpent: 0,
  },
  {
    id: 16,
    budgetCategory: 'Loan',
    amountBudgeted: 1000,
    amountSpent: 0,
  },
  {
    id: 17,
    budgetCategory: 'Miscellaneous',
    amountBudgeted: 1000,
    amountSpent: 0,
  },
];
